### ISSUE TITLE
Autoplay won't work if window is not focused

### ISSUE THREAD

**Issue by graphee-gabriel** [tjallingt/react-youtube#146]
I'm working on an app that generates a new youtube player each time the previous one finishes the video, kind of like a playlist.
Everything works well when I'm focusing the window.
But as soon as I switch to another the tab, the playlist will stop at the end of the video, and start again only if i go back to focusing this tab.

Any idea?

**Comment by tjallingt** [comment]
hey @graphee-gabriel, 

Sorry for the delayed response, I have not encountered this issue...
Browsers are cracking down on sites that are autoplaying content however so I imagine that might have something to do with it...

> generates a new youtube player

Are you reusing the react-youtube instance, after a user starts an instance of the youtube player as long as it exists it should continue to autoplay (if the autoplay flag is set). However if you are recreating the player every time your milage may vary
