### ISSUE TITLE
Can't scroll when mouse over video @ 7.8.0

### ISSUE THREAD

**Issue by hackhat** [tjallingt/react-youtube#169]

**Comment by hackhat** [comment]
Changed to 7.5.0 and works perfectly. There is some regression or different options.

      opts: {
        width: `100%`,
        playerVars: { // https://developers.google.com/youtube/player_parameters
          autoplay: 0,
          modestbranding: 1,
          listType: `playlist`,
          list: `xxxx`,
        },
      },

**Comment by jonathangiamp** [comment]
Same problem here on Chrome. Anyone have a solution?

**Comment by davidecarpini** [comment]
If you don't need to click the video you can wrap it with a pointer-events: none
<div style={{ pointerEvents: 'none' }}>
	<YouTube
		videoId=""
		opts={opts}
	/>
</div>

**Comment by hackhat** [comment]
Yeah, that's ok, but I need people to play and pause. Thanks anyway

**Comment by vulehai** [comment]
I have the same problem, if you have any solution please help me! Thank you!

**Comment by ruisaraiva19** [comment]
Looks like this isn't a problem anymore.
