### ISSUE TITLE
Type definitions for PlayerState

### ISSUE THREAD

**Issue by karolisgrinkevicius-home24** [tjallingt/react-youtube#189]
Thanks for this great library first of all. I'm working with TS a lot and there's something that I missed in type definitions.

`@types/react-youtube` is missing definitions for `PlayerState` object. Could you please add it to the `DefinitelyTyped` next release?

**Comment by ruisaraiva19** [comment]
@karolisgrinkevicius-home24 A pull request with the base type definitions was merged today. I and @tjallingt are working on migrating the codebase to TypeScript as we speak in order to make the library fully typed.
