### ISSUE TITLE
Control over width but not height (stuck at 150px)

### ISSUE THREAD

**Issue by foureyedraven** [tjallingt/react-youtube#192]
Hi,

EDIT to point out I'm on React Native (edit: React Native Web 0.10.0).

For some reason I don't have full control over the height of the iframe created to show a youtube video. The height is restricted to 150px no matter what I do, 150px being the default to iframe. For some reason, I do have control over the width. 

My code is very simple:

```javascript
import YouTube from 'react-youtube';

...
    const opts = {
      }
...
      <View style={[styles.alignCenter, styles.mb30]}>
          <YouTube
            id='video'
            videoId={this.props.videoUrl}
            opts={opts}
          />
    </View>
```

I've tried a lot of permutations of the height and width. 

If I put in width 100%, then the frame shrinks to default 300x150 that iframe has. With no dimensions set, I get the full width, but with the height still restricted. 

I've tried things like changing absolute position, setting height to 200%, but nothing has worked. Toggled some base iframe settings in the app as well, no change.

**Comment by diegoaguilar** [comment]
Did you find a workaround for this?

**Comment by ScottAgirs** [comment]
> Hi,
> 
> EDIT to point out I'm on React Native (edit: React Native Web 0.10.0).
> 
> For some reason I don't have full control over the height of the iframe created to show a youtube video. The height is restricted to 150px no matter what I do, 150px being the default to iframe. For some reason, I do have control over the width.
> 
> My code is very simple:
> 
> ```js
> import YouTube from 'react-youtube';
> 
> ...
>     const opts = {
>       }
> ...
>       <View style={[styles.alignCenter, styles.mb30]}>
>           <YouTube
>             id='video'
>             videoId={this.props.videoUrl}
>             opts={opts}
>           />
>     </View>
> ```
> 
> I've tried a lot of permutations of the height and width.
> 
> If I put in width 100%, then the frame shrinks to default 300x150 that iframe has. With no dimensions set, I get the full width, but with the height still restricted.
> 
> I've tried things like changing absolute position, setting height to 200%, but nothing has worked. Toggled some base iframe settings in the app as well, no change.



> Did you find a workaround for this?


You could try something along the lines of this:

```
    width: 100vh;
    height: calc(100vh / 1.75);
```

**Comment by brunocalou** [comment]
I had the same problem using it on web.
The problem is that from version 7.8.0 to 7.9.0 a div tag was added between YouTube component and the iframe tag

I believe it was caused by this commit: 0865bdd58a6a55bffc7fca7f1302ba9a179cf5fa

To solve it immediately, I forced this div to have height: 100%

```css
> * {
    height: 100%;
  }
```

**Comment by dcorb** [comment]
We use this: 
```
/**
 * Uses the padding technique to have a responsive full width video.
 */
const VideoIframeWrapper = styled.div`
  div {
    padding-top: 56.25%;
    position: relative;
    iframe {
      position: absolute;
      top: 0;
      left: 0;
    }
  }
`;
```
