### ISSUE TITLE
Authenticate Private Videos with react-youtube?

### ISSUE THREAD

**Issue by ScottAgirs** [tjallingt/react-youtube#194]
Is it possible and if not, is it on the road map to authenticate private videos with this component to be able to stream those via one's app?

Cheers for the good work.

**Comment by ruisaraiva19** [comment]
@ScottAgirs The [IFrame Player API](https://developers.google.com/youtube/iframe_api_reference) documentation doesn't reference any option to authenticate a user in order to play private videos.
