### ISSUE TITLE
showinfo is not working

### ISSUE THREAD

**Issue by Marcuspo** [tjallingt/react-youtube#198]
const videoOptionsPre = {
    width: "100%",
    height: "455",
    playerVars: {
      // https://developers.google.com/youtube/player_parameters
      controls: 0,
      autoplay: play,
      modestbranding: 1,
      rel: 0,
      disablekb: 1,
      showinfo: 0,
    }
  };

but showinfo not working and show title in video.

**Comment by harrison0723** [comment]
The parameter's deprecated.

https://developers.google.com/youtube/player_parameters#showinfo

**Comment by Marcuspo** [comment]
where do you report that it was discontinued?

**Comment by ndom91** [comment]
@Marcuspo you as the consumer dont report it anywhere. Google tells us when / if stuff gets deprecated and we need to adjust our implementations accordingly. 

If you mean where to report this deprecation to this react component, if there is an implementation in the component of this option, your best bet is to simply make a pull request yourself and remove the functionality and/or maybe replace it with something functional / more modern.
