### ISSUE TITLE
startSeconds does not work

### ISSUE THREAD

**Issue by ray-4dvw** [tjallingt/react-youtube#199]
This is how i set it up.  But seems both start and end are not working.   
 
```
  const opt = {
    playerVars: {
      start: 50,
    },
  };
```
 
     <YouTube
        opt={opt}
        onReady={onReady}
        videoId="RGu5wTuPo5g" 
      />

**Comment by ray-4dvw** [comment]
I found a  work around
```
const onPlayVideo = () => {
    ytPlayer.playVideo();
    ytPlayer.seekTo(30);
  };
```

**Comment by kemenyadi** [comment]
Is it not `opts`

**Comment by jkoontz2010** [comment]
The first load of a video doesn't use start properly. If I put another video in its place (user clicks on another video, video is loaded into YouTube component), then start works all of a sudden
