### ISSUE TITLE
onReady callback Typescript type

### ISSUE THREAD

**Issue by rdalfonso** [tjallingt/react-youtube#202]
What should the TypeScript type be for the onReady callback method?
Using Event doesn't make the methods accessible.
'Any' seems to work but I'd like to know what the Type should be.
**Note:** I do have @types/react-youtube installed.

Thanks

` &lt;YouTube
        videoId="2g811Eo7K8U"
        opts={opts}
        onReady={this.onReady} &gte;
      

onReady(event: _Event_??) {
    // access to player in all event handlers via event.target
    event.target.pauseVideo();
  }`

**Comment by ruisaraiva19** [comment]
@rdalfonso A pull request with the base type definitions was merged today. I and @tjallingt are working on migrating the codebase to TypeScript as we speak in order to make the library fully typed.
