### ISSUE TITLE
How to get reference a reference to a video player

### ISSUE THREAD

**Issue by lukbrt** [tjallingt/react-youtube#211]
Hello,

Does this component allows to get reference to a particular video player and call stopVideo() method on it? I need to embed the video component inside modal and I would like to stop the video whenever the user closes the modal, but I can't see any information in react-youtube documentation. There is reference to Youtube API documentation, but there they just reference to player object, but I can't access this object when using the react-youtube component.

**Comment by rantoniops** [comment]
I have the same issue :(

**Comment by appac** [comment]
I think you might want [Refs](https://reactjs.org/docs/refs-and-the-dom.html) for achieving this. I currently use a ref to trigger the video to play when another element is clicked. Crate a ref in the component, then attach that ref to the video element. It'll then be accessible via that ref.

I threw together an [example here](https://codesandbox.io/s/fervent-pare-xgnzd), if it helps!

**Comment by ruisaraiva19** [comment]
@appac thanks for helping and providing a solution. @rantoniops @lukbrt did @appac's solution solved your issues?

**Comment by rorz** [comment]
As @appac pointed out, you need to use a `ref` to the player in order to control it. However, it seems like the the player is nested inside an `internalPlayer` object (within the ref) so it's not super intuitive.

I'm using hooks (if you're using classes follow @appac's solution above), and arrived at this:

```jsx
import React, { useRef } from "react";
import YouTube from "react-youtube";

// ...

const MyComponent = () => {
  // Initialises a 'ref' for the player
  const playerRef = useRef(null);

  // You can now access the player in your component
  // by using "playerRef.current.internalPlayer.API_METHOD"
  // ... See below for an example:

  // Our own custom function to pause the video
  const pauseVideo = () => {
    playerRef.current.internalPlayer.pauseVideo();
  };

  return (
    <>
      {/* Rest of your component */}
      <YouTube
        id="YOUR_VIDEO_ID"
        // Your other props
        ref={playerRef} // This sets the ref above to be linked to the player now
      />
      {/* Using a button to pause the video, for example */}
      <button onClick={pauseVideo}>Pause Video</button>
    </>
  );
};

```

**Comment by florianuphoff** [comment]
Interesting solution @rorz 👍 

I'm using `react-youtube` with TypeScript but the `internalPlayer` does not exist on the exported type `YouTube`. It still works but it does not bundle. 

![Screenshot 2020-04-21 at 07 29 55](https://user-images.githubusercontent.com/33223518/79828865-f4e76480-83a1-11ea-8ee8-704cb2acff19.png)


I'm going to create a PR to add the internalPlayer to the exported types. Hopefully this will fix it. Maybe this should be added to the docs as well? In my opinion it's a very important feature but difficult to find out how it works

**Comment by randak** [comment]
Rather than using a ref, you can store the value of the `onReady` function in state as a kind of callback. After that, you can use `video.playVideo()` and other functions as expected.

```
const [video, setVideo] = useState(undefined)

const handleReady = event => setVideo(() => event.target)

return (
  <Youtube videoId={videoId} onReady={handleReady} />
)
```

**Comment by Wmitrut** [comment]
Ok, @florianuphoff I find a solution... If I use `useRef ` like this with typescript:

` const playerRef = useRef<any>();`

and then call my method:

` playerRef?.current?.internalPlayer.stopVideo();`

---- 

I know it is not the best one but worked fine for me.
