### ISSUE TITLE
Allow modifying tabIndex and other props?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [tjallingt/react-youtube#212]
Hi, thanks for this great package!

Because of https://github.com/davidtheclark/focus-trap/issues/57, in my usage of `react-youtube` I need to set the iframe's `tabIndex = 0`:

```jsx
<YouTube
  onReady={event => {
    // See https://github.com/davidtheclark/tabbable/issues/23
    // We use tabbable via focus-trap via focus-trap-react
    event.target.a.tabIndex = '0';
  }}
  videoId={youtubeId}
  opts={videoOptions}
/>
```

Not ideal. Could this package please allow either:

* _(preferred)_ An `iframeProps` object of attributes to give to the iframe?
* Failing that, calling that iframe `iframe` in the target, instead of the closure-minified `a`?

I'm happy to contribute these changes if you're ok with them!

**Comment by ruisaraiva19** [comment]
@JoshuaKGoldberg Thank you for providing the context for this issue.

I think adding a new prop `iframeProps` would be a nice way to provide this functionality without introducing breaking changes. Also, the name can be more specific by being called `iframeAttrs` but either way it's fine.

Feel free to open a pull request with the `iframeProps/iframeAttrs` prop added. 😉

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues in repos that haven't had updates in a few years. Cheers!
