### ISSUE TITLE
Improve release workflow

### ISSUE THREAD

**Issue by tjallingt** [tjallingt/react-youtube#216]
Releases are currently quite "loose".
I'd like to have more structure so we know when to release which version/features/fixes (tracking issue or board/project/milestone)
This should also include maintaining a changelog for example.

While I'm not yet entirely sold on fully automating releases it would be great to get started with setting up semantic release (at least changelog generation on release)

Not sure what this entails yet so if you (anyone) have more info or wants to help implement that would be awesome.

**Comment by ruisaraiva19** [comment]
@tjallingt I have a couple of projects with semantic releases configured. All commits follow the conventional commits specification and on each push to the release branch, a CI workflow builds the project, releases a new version (tag) and generates a changelog.

**Comment by tjallingt** [comment]
Sounds great! I figured I'd create this mostly as a tracking issue (and since I'm bad at releasing stuff properly xD)

**Comment by ruisaraiva19** [comment]
@tjallingt this is now up and running. We can close this issue now.
