### ISSUE TITLE
version 7.10.0 breaks CRA production build

### ISSUE THREAD

**Issue by franjorub** [tjallingt/react-youtube#227]
Hi today I did a build in my remote server and I get this error 

Failed to minify the code from this file:         
remote:                
remote:         	./node_modules/react-youtube/dist/index.esm.js:86         
remote:                
remote:        Read more here: http://bit.ly/2tRViJ9  

downgrading to version 7.9.0 works again

**Comment by ruisaraiva19** [comment]
@franjorub Can you provide more details like the version of `react-scripts` you are using?

I have just created a new project with CRA, added `react-youtube@7.10.0` and it built with no problems.

**Comment by MateuszKuba** [comment]
The problem is connected with NODE JS version. Version 7.10.0 requires NODE V12 however Version 7.9.0 required Node V10 or above, my code is breaking as well however it is because of the NODE JS version on the server not the upgrade itself

For example AWS amplify has NodeV10 in standard of their deployment

**Comment by ruisaraiva19** [comment]
> The problem is connected with NODE JS version. Version 7.10.0 requires NODE V12 however Version 7.9.0 required Node V10 or above, my code is breaking as well however it is because of the NODE JS version on the server not the upgrade itself
> 
> For example AWS amplify has NodeV10 in standard of their deployment

A [PR is already opened](https://github.com/tjallingt/react-youtube/pull/228) for this 🙂.

**Comment by franjorub** [comment]
Hi! sorry for the delay I forgot include that information in the issue, 

    "react-scripts": "1.1.4",

node V12.14.1 - local
node V12.16.1 - server

both fails
