### ISSUE TITLE
Incompatible version of yarn

### ISSUE THREAD

**Issue by kylemh** [tjallingt/react-youtube#233]
I was unable to install dependencies in Netlify because they use an older version of yarn.

I HIGHLY doubt there's anything wrong with `1.16.0`, can you please remove the engine requirements for `yarn`?

I've added `YARN_VERSION` to my build envs to use a more modern version of yarn, but my upgrade was also broken last week by an engine required version of Node... then that was reverted.

Is there good reason to add these engine tags beyond `^10.x` for Node?

**Comment by ruisaraiva19** [comment]
@kylemh I'm glad you were able to fix the Yarn issue on Netlify by adding the `YARN_VERSION` environment variable.
We require Node.js version 10 at least now because of Node.js version 8 reached the end of life on December 31, 2019.

**Comment by kylemh** [comment]
Sure, I get required Node 10.x, but why specify a specific version beyond that and why specify a specific version of yarn?

**Comment by axe312ger** [comment]
This yarn engine requirement can break tests running in alpine linux node dockers as they might come with older yarn versions. I run into this lately as I use the following github action to run my tests: https://github.com/stefanoeb/jest-action

Is there any reason you require yarn at all for this module? Why does it not work with npm or older versions of yarn? It was working fine with an old yarn in my projects for several months :)

**Comment by kylemh** [comment]
@axe312ger I use yarn to install dependencies. I was on some slightly older version and it prevented me from installing the dep in CI and locally until I upgraded.

**Comment by kylemh** [comment]
@ruisaraiva19 I feel like you should remove the requirement for a specific version of yarn. I doubt it affects local development.

**Comment by axe312ger** [comment]
Thank you! <3
