### ISSUE TITLE
It automatically switches to full-screen mode when I click a video on the iphone

### ISSUE THREAD

**Issue by charach** [tjallingt/react-youtube#245]
When you I click on a video in the version of the iPhone SE (13.5.1), it automatically moves to full-screen mode and plays. 
Can I stop this conversion? (It works normally on Android. ) 
Also, the full-screen mode is executed when using the function seek().

**Comment by claudiopedrom** [comment]
@charach try to add:
```
playerVars: { playsinline: 1 },
```

**Comment by charach** [comment]
Thank you! I  close this issue.
