### ISSUE TITLE
As today it seems like the event is not triggered.

### ISSUE THREAD

**Issue by XzaR90** [tjallingt/react-youtube#260]
As today it seems like the events is not triggered.

OnReady event is not firing at all. Does it have to do with same site cookie policies?

**Comment by kimchouard** [comment]
+1, same here events (onReady, onStateChange, etc.) are not trigerring.

**Comment by kimchouard** [comment]
@XzaR90 seems like the timing of your comment aligns with a Youtube Data API release (see [revision history for Sept. 9](https://developers.google.com/youtube/v3/revision_history)). But I don't anything in their list that would compromise the iframe events 🤔

**Comment by jpbretanha** [comment]
+1

**Comment by XzaR90** [comment]
Ahh okey, I does seems to work in old edge browser, have not tested with Firefox.
