### ISSUE TITLE
Play / Pause Video

### ISSUE THREAD

**Issue by ozenesat** [tjallingt/react-youtube#263]
I was wondering if there is a way to pause and play the video while the user interacting with some other stuff on my page. Mute / Unmute works too. I couldn't find an ideal callback for it, but if anyone knows a way, I truly appreciate it.

**Comment by jrajav** [comment]
@ozenesat Yep, it's possible by using the element reference itself from the onReady callback - see the official example to see one way to do it: https://github.com/tjallingt/react-youtube/blob/master/example/example.js

**Comment by ozenesat** [comment]
ty @jrajav !
