### ISSUE TITLE
How to add time point as prop?

### ISSUE THREAD

**Issue by pravosleva** [tjallingt/react-youtube#274]
Hello. Anybody help me?
Or maybe this should be feature request?

**Comment by ruisaraiva19** [comment]
@pravosleva you can use the [`start`](https://developers.google.com/youtube/player_parameters#start) property inside the `playerVars` options property.

```jsx
const opts = {
  height: '390',
  width: '640',
  playerVars: {
    start: 10, // begin playing the video at the given number of seconds from the start of the video
  },
};

return <YouTube videoId="2g811Eo7K8U" opts={opts} />;
```
