### ISSUE TITLE
How to stop another videos when current video is playing

### ISSUE THREAD

**Issue by bocanhcam** [tjallingt/react-youtube#304]
I have multiple videos on a page.

When I play first video then second video.

Both are played.

I want to stop first video while playing second video.

Can any one help. please! Thank you!

**Comment by oksimilk** [comment]
I ran into a similar problem and could not find the api in the current package

My solution is to use `internalPlayer.pauseVideo()`

First, create a stack and store the current video id in it
Then we access the player via ref
Check if the current video id value has changed, and if so, stop player.current.internalPlayer.pauseVideo()
