### ISSUE TITLE
Error when building with CRA

### ISSUE THREAD

**Issue by dbuchet** [tjallingt/react-youtube#378]
I've updated to version `10.0.0` and have this error on build with `react-scripts`

```
./node_modules/react-youtube/dist/YouTube.mjs
Can't import the named export 'jsx' from non EcmaScript module (only default export is available)
```

I haven't changed anything from when using version `9.0` and seeing changelog, nothing is supposed to have changed 🤔 

ps: Don't think it's related, but i'm obviously using `react@18`

**Comment by dantabel** [comment]
+1 
My full error message is:
```
Compiled with problems:

ERROR in ./node_modules/react-youtube/dist/YouTube.mjs 6:0-40

Module not found: Error: Can't resolve 'react/jsx-runtime' in 'C:\Users\XXXXX\XXX\node_modules\react-youtube\dist'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```
react: 16.14.0
react-scripts: 5.0.1
react-youtube: 10.0.0

**Comment by ibrahimyaacob92** [comment]
getting same issue here

**Comment by philippechevieux** [comment]
Same issue for me. Has anyone been able to solve it?

**Comment by ruisaraiva19** [comment]
> I've updated to version `10.0.0` and have this error on build with `react-scripts`
> 
> ```
> ./node_modules/react-youtube/dist/YouTube.mjs
> Can't import the named export 'jsx' from non EcmaScript module (only default export is available)
> ```
> 
> I haven't changed anything from when using version `9.0` and seeing changelog, nothing is supposed to have changed 🤔
> 
> ps: Don't think it's related, but i'm obviously using `react@18`

@dbuchet whats the version of `react-scripts` that you are using?

**Comment by ruisaraiva19** [comment]
> jsx-runtime

@dantabel when using `react-youtube` 10.0.0+, at least React version 17+ is required in order to have the `jsx-runtime` available.

**Comment by dbuchet** [comment]
> > I've updated to version `10.0.0` and have this error on build with `react-scripts`
> > ```
> > ./node_modules/react-youtube/dist/YouTube.mjs
> > Can't import the named export 'jsx' from non EcmaScript module (only default export is available)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I haven't changed anything from when using version `9.0` and seeing changelog, nothing is supposed to have changed 🤔
> > ps: Don't think it's related, but i'm obviously using `react@18`
> 
> @dbuchet whats the version of `react-scripts` that you are using?

I'm using `react-scripts@4.0.3`
Is `5.x.x` now mandatory? Because this indeed looks like a breaking change for me :)

**Comment by ruisaraiva19** [comment]
> > > I've updated to version `10.0.0` and have this error on build with `react-scripts`
> > > ```
> > > ./node_modules/react-youtube/dist/YouTube.mjs
> > > Can't import the named export 'jsx' from non EcmaScript module (only default export is available)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I haven't changed anything from when using version `9.0` and seeing changelog, nothing is supposed to have changed 🤔
> > > ps: Don't think it's related, but i'm obviously using `react@18`
> > 
> > 
> > @dbuchet whats the version of `react-scripts` that you are using?
> 
> I'm using `react-scripts@4.0.3` Is `5.x.x` now mandatory? Because this indeed looks like a breaking change for me :)

Not mandatory, just to know for testing purposes.

I opened a [PR](https://github.com/tjallingt/react-youtube/pull/382) with a fix.

**Comment by ruisaraiva19** [comment]
@dbuchet @angela318 @dantabel @ibrahimyaacob92 @philippechevieux can you please test again with version `10.1.0`?

**Comment by philippechevieux** [comment]
@ruisaraiva19 It is working great now thank you 👍

**Comment by ruisaraiva19** [comment]
> @ruisaraiva19 It is working great now thank you 👍 

Great, thanks for testing!
