### ISSUE TITLE
Can't import the named export 'jsx' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by adcoding** [tjallingt/react-youtube#381]
React with Javascript
Why do I get this error?

./node_modules/react-youtube/dist/YouTube.mjs
Can't import the named export 'jsx' from non EcmaScript module (only default export is available)

**Comment by ruisaraiva19** [comment]
@adcoding can you please test again with version `10.1.0`?

**Comment by adcoding** [comment]
@ruisaraiva19 yeah it's working now... thank you
